version: '2'

services:
  jekyll:
    image: jekyll/jekyll:3.5
    command: jekyll serve --watch --drafts --force_polling --verbose
    ports:
      - 4000:4000
      - 35729:35729
    volumes:
      - ./jekyll/:/srv/jekyll
    environment:
      - VIRTUAL_HOST=www.robotarleksaker.se,robotarleksaker.se
      - JEKYLL_ENV=production
      - VIRTUAL_PORT=4000

      
networks:
  default:
    external:
      name: nginx-proxy